apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

configMapGenerator:
- name: environment
  behavior: merge
  literals:
  - BASE_HOSTNAME=.brandmuscle.net
  - BMIAPPS_STORAGE_URL=bmiappsprod.z20.web.core.windows.net
