apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

configMapGenerator:
- name: environment
  behavior: merge
  literals:
  - BASE_HOSTNAME=v5qa.brandmuscle.net
  - BMIAPPS_STORAGE_URL=bmiappsqa.z20.web.core.windows.net
